### PR TITLE
[iOS] Request the file data from file providers

### LINKED ISSUE #1549: [Bug] iOS FilePicker.PickAsync throws FileNotFoundException when file selected from 3rd party cloud service
### Description
When a file is selected from a 3rd party cloud service, such as Google Drive or OneDrive (iCloud seems to work fine), a `FileNotFoundException` is thrown before `PickAsync` returns.

Exception details:
System.IO.FileNotFoundException
  Message=Could not find file "/private/var/mobile/Containers/Shared/AppGroup/CEAC05E9-B03E-4466-84E5-A760E27B9EA2/File Provider Storage/78133883/1KKmRqZQRYaNsgKwo3GPqgG-LLuqxO12z/signature.png"

Stack trace:
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0026e] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.IO/FileStream.cs:274 
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/corlib/System.IO/FileStream.cs:91 
  at System.IO.File.OpenRead (System.String path) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/external/corefx/src/System.IO.FileSystem/src/System/IO/File.cs:266 
  at Xamarin.Essentials.UIDocumentFileResult..ctor (Foundation.NSUrl url) [0x00047] in D:\a\1\s\Xamarin.Essentials\FileSystem\FileSystem.ios.cs:24 
  at Xamarin.Essentials.FilePicker+<>c.<PlatformPickAsync>b__2_1 (Foundation.NSUrl url) [0x00000] in D:\a\1\s\Xamarin.Essentials\FilePicker\FilePicker.ios.cs:39 
  at System.Linq.Enumerable+SelectArrayIterator`2[TSource,TResult].MoveNext () [0x0003a] in <981796af34bc41bbb400a76739b97f16>:0 
  at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x00045] in <981796af34bc41bbb400a76739b97f16>:0 
  at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in <981796af34bc41bbb400a76739b97f16>:0 
  at Xamarin.Essentials.FilePicker.PickAsync (Xamarin.Essentials.PickOptions options) [0x0001c] in D:\a\1\s\Xamarin.Essentials\FilePicker\FilePicker.shared.cs:12 

### Steps to Reproduce
1. Open a file picker via `FilePicker.PickAsync`
2. Select a file from a 3rd party cloud service (ie. not iCloud) - tested with Google Drive and OneDrive

### Expected Behavior
`PickAsync` returns a `FileResult` representing the selected file.

### Actual Behavior
A `FileNotFoundException` is thrown and thus `PickAsync` does not return.

### Basic Information
- Version with issue: 1.6.0-pre*
- Platform Target Frameworks: iOS
  - iOS:  14.2.0.12
- Affected Devices: iPhone/iPad (found on iOS 14 device)

### PR DESCRIPTION
**Pull request by mattleibow**
### Description of Change ###

This PR will make sure that when files are picked, they are read correctly. Typically, external apps can provide file using a file provider, so we need to make sure we use that file provider to read the file data.

This PR also fixes a memory leak. Previously, the file was picked and opened. This also had a limitation that once the stream is closed then it can never be opened. And, multiple opens will cause issues with the single stream.

### Bugs Fixed ###

- Fixes #1549

### API Changes ###
None.

### Behavioral Changes ###

When picking files from third party providers, request the data from the provider.

### CODE REVIEW

File: Samples/Samples/ViewModel/FilePickerViewModel.cs [hunk 1]
```diff
@@ -136,12 +136,16 @@ async Task<FileResult> PickAndShow(PickOptions options)
 
                 if (result != null)
                 {
-                    Text = $"File Name: {result.FileName}";
+                    var size = await GetStreamSizeAsync(result);
+
+                    Text = $"File Name: {result.FileName} ({size:0.00} KB)";
 
                     if (result.FileName.EndsWith("jpg", StringComparison.OrdinalIgnoreCase) ||
+                        result.FileName.EndsWith("jpeg", StringComparison.OrdinalIgnoreCase) ||
```
Comment (spouliot) [inline Samples/Samples/ViewModel/FilePickerViewModel.cs:144]: Not new to your PR but since you're fixing it :)
A file named `This-is-not-a-jpeg` would hit that condition.
You should use https://docs.microsoft.com/en-us/dotnet/api/system.io.path.getextension?view=net-5.0

File: Samples/Samples/ViewModel/FilePickerViewModel.cs [hunk 2]
```diff
@@ -136,12 +136,16 @@ async Task<FileResult> PickAndShow(PickOptions options)
 
                 if (result != null)
                 {
-                    Text = $"File Name: {result.FileName}";
+                    var size = await GetStreamSizeAsync(result);
```
Comment (spouliot) [inline Samples/Samples/ViewModel/FilePickerViewModel.cs:139]: it seems inefficient to open the stream twice. First here to get the size.

then later (if an image) to read it's content.

**Review by spouliot — COMMENTED** [review]
LGTM

File: Samples/Samples/ViewModel/FilePickerViewModel.cs (hunk 2 above)
Comment (mattleibow) [reply Samples/Samples/ViewModel/FilePickerViewModel.cs:139]: That is partially the point. I want to test a double open and close of the stream.

Comment (spouliot) [reply Samples/Samples/ViewModel/FilePickerViewModel.cs:139]: yep. but it's not obvious (no comment) and sample code tends to be copy/pasted into prod apps
still meant it as something quite minor :)
